### ISSUE TITLE
Web IDE has some strange behaviours

### ISSUE THREAD

**Issue by ouuan** [EtherOJ/EtherOJ#1]
Sometimes unexpected spaces are inserted. It doesn't always happen, so I'm not sure how to reproduce it. But it always happen if I type some codes.

**Comment by diauweb** [comment]
I can't reproduce. Additional infomation is required.

**Comment by ouuan** [comment]
I met this 5 minutes ago:

1.  Delete everything.
2.  Type:
    ```cpp
    #include <iostream>
    #include <cstdio>
    
    
    ```
3.  Type: `u`.
4.  Got:
    ```cpp
    #include <iostream>
    #include <cstdio>
    
    
    u
    ```
    (There's one unexpected newline inserted when typing `u`.)

But I can't reproduce it now :thinking:

**Comment by ouuan** [comment]
We can close this until someone has found a stable way to reproduce it.
