### ISSUE TITLE
Problem in URL or URL parameter of the submit page

### ISSUE THREAD

**Issue by ouuan** [EtherOJ/EtherOJ#2]
Now I don't know how to visit the submit page of a certain problem by the URL. Something like `/submit/<repo>/<reference>` or `/submit?repo=<repo>&reference=<reference>` will be great.

**Comment by diauweb** [comment]
changes apply to problem details page too. now you can visit problems in any repo now. 
see 75abb9b9f0ddbb2c13f5f7ca5c96eab8ba07b368
